name: jetson-tx1
version: '1'
summary: jetson-tx1 gadget
base: core18
description: |
 Bootloader files and partitoning data to create a
 bootable Ubuntu Core image for the jetson TX1 device
type: gadget
architectures:
  - arm64
confinement: strict
grade: stable

parts:
  uboot:
    plugin: nil
    source: git://nv-tegra.nvidia.com/3rdparty/u-boot.git
    source-type: git
    source-tag: tegra-l4t-r28.2
    override-pull: |
      snapcraftctl pull
      # Apply UC patches + bug fixes
      git am ../../../../uboot-patch/*.patch
    override-build: |
      export ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-
      make p2371-2180_defconfig
      nice make -j$(nproc)
      cp "$SNAPCRAFT_PART_BUILD"/u-boot.bin "$SNAPCRAFT_PART_INSTALL"/

  uboot-env:
    plugin: nil
    source: ../uboot-env
    override-build: |
      mkenvimage -r -s 131072 -o uboot.env uboot-tx1.env.in
      cp "$SNAPCRAFT_PART_BUILD"/uboot.env "$SNAPCRAFT_PART_INSTALL"/
      # Link needed for ubuntu-image to work properly
      cd "$SNAPCRAFT_PART_INSTALL"/; ln -s uboot.env uboot.conf
    build-packages:
      - u-boot-tools
